apiVersion: apps/v1
kind: Deployment
metadata:
 name: mynginx-deploy
 labels:
   app: mynginx
spec: 
  replicas: 3
  selector:
      matchLabels:
        app: mynginx
  template:
     metadata:
       labels:
        app: mynginx
     spec:
      containers:
      - name: mynginx-container
        image:  nginx
        ports:
        - containerPort: 8080
